"use client"

import { useState } from "react"
import { Download, FileText, FileSpreadsheet, FileCode, Plus, Calendar, Loader2, X } from "lucide-react"
import { Card, CardHeader, PageHeader } from "@/components/dashboard/ui"
import { useAppData, addNotification, addAuditLog } from "@/lib/use-app-data"
import { useAuth } from "@/lib/auth-context"
import { supabase } from "@/lib/supabase-client"
import { formatDateTime, nowISO, relativeFromISO } from "@/lib/datetime"
import { cn } from "@/lib/utils"

function formatIcon(format: string) {
  if (format === "xlsx") return { Icon: FileSpreadsheet, color: "#2dd4bf" }
  if (format === "csv") return { Icon: FileCode, color: "#38bdf8" }
  return { Icon: FileText, color: "#f0596b" }
}

const templates = [
  { name: "Executive Summary", desc: "High-level posture for leadership", cadence: "Monthly", type: "executive" },
  { name: "Compliance Attestation", desc: "Per-framework control evidence", cadence: "Quarterly", type: "compliance" },
  { name: "Findings Digest", desc: "All open findings with remediation", cadence: "Weekly", type: "findings" },
]

export default function ReportsPage() {
  const { reports, findings, devices, postureScore, severityCounts, refresh } = useAppData()
  const { profile, tenant } = useAuth()
  const [generating, setGenerating] = useState<string | null>(null)
  const [showGenModal, setShowGenModal] = useState(false)
  const [genTitle, setGenTitle] = useState("Executive Security Posture Summary")
  const [genType, setGenType] = useState("executive")
  const [genFormat, setGenFormat] = useState("pdf")

  async function generateReport(template?: { name: string; type: string }) {
    if (!tenant || !profile) return
    const title = template?.name ?? genTitle
    const type = template?.type ?? genType
    const format = genFormat
    setGenerating(type)

    const reportData = {
      postureScore,
      complianceCoverage: postureScore,
      devices: devices.length,
      findings: findings.length,
      severityCounts,
      topFindings: findings.slice(0, 10).map((f) => ({
        device: f.device_name,
        vendor: f.vendor,
        severity: f.severity,
        issue: f.issue,
        framework: f.framework,
        status: f.status,
      })),
      generatedBy: profile.full_name,
      companyName: tenant.name,
    }

    const { data: report } = await supabase.from("reports").insert({
      tenant_id: tenant.id,
      title,
      type,
      format,
      report_data: reportData,
      generated_at: nowISO(),
    }).select().single()

    await addNotification(tenant.id, profile.id, "report_generated", "Report generated", `"${title}" is ready for download.`, "/reports")
    await addAuditLog(tenant.id, profile.id, profile.full_name, "report_generated", "report", report?.id, { title, format })

    setGenerating(null)
    setShowGenModal(false)
    refresh()
  }

  function downloadReport(report: typeof reports[0]) {
    const data = report.report_data ?? {}
    const lines: string[] = []

    lines.push("SECURENORM AI — SECURITY REPORT")
    lines.push("=".repeat(50))
    lines.push("")
    lines.push(`Report ID: ${report.id}`)
    lines.push(`Title: ${report.title}`)
    lines.push(`Type: ${report.type}`)
    lines.push(`Generated: ${formatDateTime(report.generated_at)}`)
    lines.push(`Company: ${tenant?.name ?? "—"}`)
    lines.push(`Generated by: ${profile?.full_name ?? "—"}`)
    lines.push("")
    lines.push("POSTURE SUMMARY")
    lines.push("-".repeat(30))
    lines.push(`Security Posture: ${data.postureScore ?? "—"}/100`)
    lines.push(`Compliance Coverage: ${data.complianceCoverage ?? "—"}`)
    lines.push(`Devices: ${data.devices ?? 0}`)
    lines.push(`Total Findings: ${data.findings ?? 0}`)
    lines.push(`  Critical: ${data.severityCounts?.critical ?? 0}`)
    lines.push(`  High: ${data.severityCounts?.high ?? 0}`)
    lines.push(`  Medium: ${data.severityCounts?.medium ?? 0}`)
    lines.push(`  Low: ${data.severityCounts?.low ?? 0}`)
    lines.push("")
    lines.push("TOP FINDINGS")
    lines.push("-".repeat(30))
    if (data.topFindings && Array.isArray(data.topFindings)) {
      data.topFindings.forEach((f: any, i: number) => {
        lines.push(`${i + 1}. [${f.severity.toUpperCase()}] ${f.issue}`)
        lines.push(`   Device: ${f.device} (${f.vendor})`)
        lines.push(`   Framework: ${f.framework} | Status: ${f.status}`)
        lines.push("")
      })
    }
    lines.push("")
    lines.push("=".repeat(50))
    lines.push("Generated by SecureNorm AI")

    if (report.format === "csv") {
      const csv = ["ID,Device,Vendor,Severity,Issue,Framework,Status"]
      if (data.topFindings && Array.isArray(data.topFindings)) {
        data.topFindings.forEach((f: any) => {
          csv.push(`"${f.device}","${f.vendor}","${f.severity}","${f.issue}","${f.framework}","${f.status}"`)
        })
      }
      const blob = new Blob([csv.join("\n")], { type: "text/csv" })
      downloadBlob(blob, `${report.title.replace(/\s+/g, "-").toLowerCase()}.csv`)
    } else {
      const blob = new Blob([lines.join("\n")], { type: "text/plain" })
      downloadBlob(blob, `${report.title.replace(/\s+/g, "-").toLowerCase()}.txt`)
    }

    addAuditLog(tenant!.id, profile!.id, profile!.full_name, "report_downloaded", "report", report.id)
  }

  function downloadBlob(blob: Blob, filename: string) {
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = filename
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <>
      <PageHeader
        title="Reports"
        description="Generate, schedule, and download audit-ready security and compliance reports across your network fleet."
      >
        <button
          onClick={() => setShowGenModal(true)}
          className="inline-flex items-center gap-2 rounded-lg bg-primary px-3 py-2 text-xs font-semibold text-primary-foreground transition hover:bg-primary/90"
        >
          <Plus className="size-3.5" />
          Generate report
        </button>
      </PageHeader>

      <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
        {templates.map((t) => (
          <Card key={t.name} className="group p-5 transition hover:border-primary/40">
            <div className="flex items-center justify-between">
              <div className="flex size-9 items-center justify-center rounded-lg border border-border/70 bg-secondary/50 text-primary">
                <FileText className="size-4" />
              </div>
              <span className="inline-flex items-center gap-1 rounded-md border border-border/70 bg-secondary/40 px-2 py-0.5 text-[11px] text-muted-foreground">
                <Calendar className="size-3" />
                {t.cadence}
              </span>
            </div>
            <h3 className="mt-3 text-sm font-semibold text-foreground">{t.name}</h3>
            <p className="mt-1 text-xs text-muted-foreground">{t.desc}</p>
            <button
              onClick={() => generateReport(t)}
              disabled={generating === t.type}
              className="mt-3 inline-flex items-center gap-1.5 rounded-lg border border-primary/30 bg-primary/10 px-2.5 py-1.5 text-xs font-medium text-primary transition hover:bg-primary/15 disabled:opacity-60"
            >
              {generating === t.type ? <Loader2 className="size-3 animate-spin" /> : <Plus className="size-3" />}
              {generating === t.type ? "Generating…" : "Generate now"}
            </button>
          </Card>
        ))}
      </div>

      <Card>
        <CardHeader title="Generated Reports" subtitle="Recently produced documents" />
        <div className="mt-2 divide-y divide-border/50">
          {reports.length === 0 ? (
            <div className="px-5 py-12 text-center">
              <FileText className="mx-auto mb-2 size-6 text-muted-foreground/40" />
              <p className="text-sm text-muted-foreground">No reports generated yet.</p>
              <p className="mt-1 text-xs text-muted-foreground/60">Click "Generate report" to create your first report.</p>
            </div>
          ) : (
            reports.map((r) => {
              const { Icon, color } = formatIcon(r.format)
              return (
                <div
                  key={r.id}
                  className="group flex items-center gap-4 px-5 py-3.5 transition-colors hover:bg-secondary/40"
                >
                  <div
                    className="flex size-10 shrink-0 items-center justify-center rounded-lg border border-border/60"
                    style={{ backgroundColor: `${color}12`, color }}
                  >
                    <Icon className="size-4" />
                  </div>
                  <div className="min-w-0 flex-1">
                    <div className="flex items-center gap-2">
                      <span className="truncate text-sm font-medium text-foreground">{r.title}</span>
                      <span className="rounded border border-border/70 bg-secondary/40 px-1.5 py-0.5 font-mono text-[10px] text-muted-foreground">
                        {r.format.toUpperCase()}
                      </span>
                    </div>
                    <div className="mt-0.5 flex flex-wrap items-center gap-x-2 gap-y-0.5 text-[11px] text-muted-foreground">
                      <span className="font-mono">{r.id.slice(0, 8).toUpperCase()}</span>
                      <span className="size-1 rounded-full bg-border" />
                      <span>{r.type}</span>
                      <span className="size-1 rounded-full bg-border" />
                      <span>{relativeFromISO(r.generated_at)}</span>
                    </div>
                  </div>
                  <div className="hidden text-right sm:block">
                    <div className="text-xs text-foreground">{formatDateTime(r.generated_at)}</div>
                  </div>
                  <button
                    onClick={() => downloadReport(r)}
                    className="inline-flex items-center gap-1.5 rounded-lg border border-border/80 bg-secondary/40 px-2.5 py-1.5 text-xs font-medium text-foreground transition hover:bg-secondary"
                  >
                    <Download className="size-3.5" />
                    Download
                  </button>
                </div>
              )
            })
          )}
        </div>
      </Card>

      {showGenModal && (
        <div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/60 backdrop-blur-sm" onClick={() => setShowGenModal(false)}>
          <div className="w-full max-w-md rounded-xl border border-border/80 bg-card/95 p-6 shadow-2xl" onClick={(e) => e.stopPropagation()}>
            <div className="mb-4 flex items-center justify-between">
              <h2 className="text-sm font-semibold text-foreground">Generate Report</h2>
              <button onClick={() => setShowGenModal(false)} className="rounded-md p-1 text-muted-foreground hover:text-foreground">
                <X className="size-4" />
              </button>
            </div>
            <div className="space-y-4">
              <div>
                <label className="mb-1.5 block text-xs font-medium text-muted-foreground">Report Title</label>
                <input
                  type="text"
                  value={genTitle}
                  onChange={(e) => setGenTitle(e.target.value)}
                  className="h-9 w-full rounded-lg border border-border/80 bg-secondary/40 px-3 text-sm text-foreground outline-none focus:border-primary/50"
                />
              </div>
              <div>
                <label className="mb-1.5 block text-xs font-medium text-muted-foreground">Type</label>
                <select
                  value={genType}
                  onChange={(e) => setGenType(e.target.value)}
                  className="h-9 w-full rounded-lg border border-border/80 bg-secondary/40 px-3 text-sm text-foreground outline-none focus:border-primary/50"
                >
                  <option value="executive">Executive Summary</option>
                  <option value="compliance">Compliance Attestation</option>
                  <option value="findings">Findings Digest</option>
                </select>
              </div>
              <div>
                <label className="mb-1.5 block text-xs font-medium text-muted-foreground">Format</label>
                <select
                  value={genFormat}
                  onChange={(e) => setGenFormat(e.target.value)}
                  className="h-9 w-full rounded-lg border border-border/80 bg-secondary/40 px-3 text-sm text-foreground outline-none focus:border-primary/50"
                >
                  <option value="pdf">PDF (text)</option>
                  <option value="csv">CSV</option>
                </select>
              </div>
              <button
                onClick={() => generateReport()}
                disabled={generating !== null}
                className="flex h-9 w-full items-center justify-center gap-2 rounded-lg bg-primary text-sm font-semibold text-primary-foreground transition hover:bg-primary/90 disabled:opacity-60"
              >
                {generating ? <Loader2 className="size-4 animate-spin" /> : null}
                {generating ? "Generating…" : "Generate"}
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  )
}
